run "rails generate devise:install"
git_add_all_and_commit_with_message "Adding Devise initializer and english locale file."

copy_template_file "devise.rb", :to => "config/initializers/devise.rb"
gsub_file "config/initializers/devise.rb", "application.com", "#{app_name.dasherize}.com"
git_add_all_and_commit_with_message "Cleaning and improving Devise initializer."

copy_template_file "devise.en.yml", :to => "config/locales/devise.en.yml"
git_add_all_and_commit_with_message "Removing initial comment and blank line from Devise english locale file."

run "rails generate devise user"
git_add_all_and_commit_with_message "Adding user files generated by Devise."

remove_dir "db/migrate/"
run "mkdir db/migrate/"
current_timestamp = Time.now.getutc.to_s.gsub(/(\s|UTC|:|-)*/, "")
copy_template_file "create_user.rb", :to => "db/migrate/#{current_timestamp}_create_users.rb"
git_add_all_and_commit_with_message "Cleaning users migration."

git :rm => "-r test/"
git_add_all_and_commit_with_message "Removing user test files."

copy_template_file "user.rb", :to => "app/models/user.rb"
git_add_all_and_commit_with_message "Cleaning user model."