source "http://rubygems.org"

gem "rails", "3.1.0"
gem "unicorn"
gem "jquery-rails"
gem "devise"
gem "inherited_resources"

group :development do
  gem "sqlite3"
  gem "foreman"
end

group :assets do
  gem "sass-rails", "~> 3.1.0"
  gem "coffee-rails", "~> 3.1.0"
  gem "uglifier"
end