source "http://rubygems.org"

gem "rails", "3.1.0"
gem "foreman"
gem "unicorn"
gem "jquery-rails"

group :development do
  gem "sqlite3"
end

group :assets do
  gem "sass-rails", "~> 3.1.0"
  gem "coffee-rails", "~> 3.1.0"
  gem "uglifier"
end

group :production do
  gem "pg"
end