source "http://rubygems.org"

gem "rails", "3.1.0"
gem "thin"
gem "sqlite3"
gem "jquery-rails"

group :assets do
  gem "sass-rails", "~> 3.1.0"
  gem "coffee-rails", "~> 3.1.0"
  gem "uglifier"
end

group :production do
  gem "pg"
end